### ISSUE TITLE
Why limit your context length to 2K rather than 4K or 8K?

### ISSUE THREAD

**Issue by yucc-leon** [InternLM/InternLM-techreport#2]
Is there any special consideration or just use it as a safe hyper-parameter as GPT-3 did?

**Comment by internlm-team** [comment]
This version of model was designed a few months ago. Long context window was not included as a development goal for this version. That being said, the extension of context window is already underway. Our future versions may support significantly longer window size.

**Comment by yucc-leon** [comment]
> This version of model was designed a few months ago. Long context window was not included as a development goal for this version. That being said, the extension of context window is already underway. Our future versions may support significantly longer window size.

Thanks for answering:)
